{
 "title": "Easy Infra",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "easy_infra ran and didn't find issues",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (labels_cwd,labels_git_branch_name,labels_git_remote_origin_url)(count_over_time({job=\"easy_infra\"} | json | line_format \"{{.log}}\" | event_type=\"allowed\"| event_outcome=\"success\" [8h]))",
     "legendFormat": "{{labels_cwd}}"
    }
   ]
  },
  {
   "title": "easy_infra found an issue but didn't fail the build",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"easy_infra\"} | json | line_format \"{{.log}}\" | event_type=\"allowed\"| event_outcome=\"failure\" [8h])) by (labels_cwd)",
     "legendFormat": "{{labels_cwd}}"
    }
   ]
  },
  {
   "title": "easy_infra didn't run security scans",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (labels_cwd,labels_git_branch_name,labels_git_remote_origin_url)(count_over_time({job=\"easy_infra\"} | json | line_format \"{{.log}}\" | event_outcome=\"unknown\" [8h]))",
     "legendFormat": "{{labels_cwd}}"
    }
   ]
  },
  {
   "title": "easy_infra failed the build",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (labels_cwd,labels_git_branch_name,labels_git_remote_origin_url)(count_over_time({job=\"easy_infra\"} | json | line_format \"{{.log}}\" | event_type=\"denied\"| event_outcome=\"failure\" [8h]))",
     "legendFormat": "{{labels_cwd}}"
    }
   ]
  },
  {
   "title": "Raw Logs",
   "type": "logs",
   "description": "Raw easy_infra logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{job=\"easy_infra\"}"
    }
   ]
  }
 ]
}