---
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 4edcbde74af0cd9b38e8483828cd9c6cb0755276  # frozen: v0.7.1
    hooks:
      - id: ruff
        types_or: [ python, pyi, jupyter ]
        args: [ --fix ]
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 0beaecb1f7500cb9c9aa54ff3ca93413d47a9a2f # freeze: v4.5.0
    hooks:
     - id: check-case-conflict
     - id: check-executables-have-shebangs
     - id: check-json
     - id: check-shebang-scripts-are-executable
     - id: check-symlinks
     - id: check-yaml
     - id: detect-aws-credentials
       args: ['--allow-missing-credentials']
     - id: detect-private-key
     - id: end-of-file-fixer
     - id: trailing-whitespace
