---
name: "CI"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: Ubuntu-22.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Run the goat
        uses: seisollc/goat@main
        with:
          exclude: '(\.css|\.scss|\.js|\.html|\.md|\.json)$|.*modules/iac_security/demo/.*|.*reveal.js/node_modules/.*|.*modules/shared/demo/demo-magic.sh$'
